---
# file: roles/common/tasks/Debian.yml

- name: Install common Debian packages
  sudo: True
  apt: pkg={{ item }} state=present
  with_items:
    - git
    - wget 
    - curl 
    - rsync 
  when: ansible_os_family == 'Debian'
  tags: common-debian-packages 
