---
# file: laptops.yml

- hosts: laptops
  connection: local
  sudo: True 
  roles:
    - common
    - java 
    - maven 
    - { role: golang, golang_path: ["/home/pinter/ext/golangthirdparty", "/home/pinter/projects/gocode"], golang_path_user: "pinter" }
    - vertx 
#    - wildfly/install
    - wildfly/uninstall
#    - wildfly/webservices 
